[project]
name = "clone-me"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "lefthook>=1.12.2",
    "ruff>=0.12.5",
    "ty>=0.0.1a16",
]
